use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - brave
      - github
      - gitlab
      - bitbucket
      - stackoverflow
      - askubuntu
      - pypi
      - npm
      - docker hub
      - mdn
      - devdocs
      - hackernews
      - arxiv
      - openalex
      - huggingface
      - ollama
      - wikipedia
      - mankier
server:
  secret_key: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
  limiter: false
search:
  formats:
    - html
    - json
